language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
before_install:
  - npm prune
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  repo: samuel-gomez-axa/samuel-gomez-axa.github.io
