language: node_js

dist: trusty

node_js:
  - '8'

branches:
  only:
    - master

install:
  - npm install

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  target-branch: master
  repo: samuel-gomez-axa/samuel-gomez-axa.github.io
  on:
    branch: master
