language: node_js

env:
  - NPM_PUBLISH_VERSION=none
  - NODE_ENV=production

node_js:
  - '8'

sudo: false

branches:
  only:
    - master

install:
  - yarn install

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - yarn run build
