language: node_js

env:
  - NODE_ENV=production

node_js:
  - '8'

sudo: false

branches:
  only:
    - master

install:
  - npm install

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - npm run build
