export default {
  pathSrc: './src',
  pathDest: './dist',
  pathImg: '/assets/images',
  pathImgDist: '/assets',
  pathFavicons: '/assets/favicons',
  jsFiles: '/**/*.js',
  sassIndex: '/index.scss',
  sassFiles: '/**/*.scss',
  pugFiles: '/*.pug',
  pugWatchFiles: '/**/*.pug',
  jsonFiles: '/data/*.json',
  pathSvg: '/assets/icons',
  svgFiles: '/*.svg',
  pathSprite: '/assets/sprite',
};
